spring:
 datasource:
  url: jdbc:mysql://localhost:3306/db1
  username: root
  password: Mihir@1
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
 application:
    name: account-manager
server:
 port: 8001

