spring:
  application:
    name: job-hunt-api-gateway
       
  cloud:
    gateway:
      routes:
      - id: accountmanager-service
        uri:
          lb://ACCOUNT-MANAGER
        predicates:
        - Path=/api/v1/userservice/**
      
      - id: watchlist-service
        uri:
          lb://JOBS-MANAGER
        predicates:
        - Path=/api/v1/jobservice/job/**
        
      - id: job-hunt-themuse-api
        uri: https://www.themuse.com/api/public/jobs?
        predicates:
        - Path=/jobs-api/**
        filters:
        - StripPrefix=1

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
          cors-configurations: 
            '[/**]':
              allowed-origins: "*"
              allowed-methods: "*"
              allowed-headers: "*"
#              allow-credentials: true
          
 
server:
     port: 8888
