spring:
 datasource:
  url: jdbc:mysql://localhost:3306/Jobdb
  username: root
  password: Mihir@1
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
 application:
  name: jobs-manager
server:
 port: 8000